# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
- name:                                "0.1 BOM Validator - Aggregate BoM Files - Informational"
  ansible.builtin.debug:
    var:                               bom_dir
    verbosity:                         1

- name:                                 "0.1 BOM Validator - Aggregate BoM Files - One time block"
  block:
    - name:                            "0.1 BOM Validator - Aggregate BoM Files - New bom name"
      when:                            this_bom_name is not defined
      ansible.builtin.set_fact:
        this_bom_name:                  "{{ bom_base_name }}{{ bom_suffix }}"

    - name:                            "0.1 BOM Validator - Aggregate BoM Files - Informational - Show BoM"
      ansible.builtin.debug:
        var:                           this_bom_name
        verbosity:                     1

    # Create download directory structure
    - name:                            "0.1 BOM Validator - Aggregate BoM Files - Create temporary BOM directories"
      delegate_to:                     localhost
      become:                          "{{ bom_processing_become }}"
      become_user:                     "{{ orchestration_ansible_user }}"
      ansible.builtin.file:
        path:                          "{{ download_directory }}/bom/{{ this_bom_name }}"
        state:                         directory
        mode:                          0755

    # Write aggregated bom
    - name:                            "0.1 BOM Validator - Aggregate BoM Files - Write aggregated BOM"
      delegate_to:                     localhost
      become:                          "{{ bom_processing_become }}"
      become_user:                     "{{ orchestration_ansible_user }}"
      ansible.builtin.copy:
        content:                       "{{ new_bom | default('NOT DEFINED') }}"
        dest:                          "{{ download_directory }}/bom/{{ this_bom_name }}/{{ this_bom_name }}.yaml"
        mode:                          0644
        force:                         true
      register:                        first_pass

# Find local bom directories
- name:                                 "0.1 BOM Validator - Aggregate BoM Files - Find files and directories"
  when:                                 bom_dir.location == 'local'
  ansible.builtin.find:
    paths:                              "{{ bom_dir.path }}"
    file_type:                          any
    recurse:                            true
  register:                             bom_directory_all_files

# Process file objects
- name:                                 "0.1 BOM Validator - Aggregate BoM Files - Process file objects"
  when:                                 bom_directory_all_files.files is defined
  ansible.builtin.include_tasks:        aggregate_bom_files.yaml
  vars:
    task_prefix:                        "0.1 BOM Validator - Aggregate BoM Files -"
    this_bom_name:                      "{{ bom_dir.path | basename }}"
  loop:                                 "{{ bom_directory_all_files.files | flatten(levels=1) }}"
  loop_control:
    loop_var:                           bom_directory_object

...
