# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

- name:                                "4.0.1.6 Hana System Replication - Ensure replication status is active"
  become_user:                         "{{ db_sid_admin_user }}"
  become:                              true
  block:

    - name:                            "4.0.1.6 Hana System Replication - Ensure replication status is active"
      when:                            ansible_hostname == primary_instance_name
      ansible.builtin.shell: |
                                       set -o pipefail
                                       (cdpy && python systemReplicationStatus.py; echo) | /usr/bin/grep -q 'overall system replication status: ACTIVE'
      register:                        grep_result
      until:                           grep_result.rc == 0 or grep_result.rc == 1
      failed_when:                     grep_result.rc != 0 and grep_result.rc != 1
      changed_when:                    false
      retries:                         10
      delay:                           5
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        PATH:                          /usr/bin/:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"

    - name:                            "4.0.1.6 Hana System Replication - Get replication status"
      when:                            ansible_hostname == primary_instance_name
      ansible.builtin.shell: |
                                       set -o pipefail
                                       (cdpy && python systemReplicationStatus.py)
      register:                        systemReplicationStatus
      failed_when:                     false
      changed_when:                    false
      vars:
        allow_world_readable_tmpfiles: true
      environment:
        PATH:                          /usr/bin/:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}:/usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        DIR_LIBRARY:                   /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        LD_LIBRARY_PATH:               /usr/sap/{{ db_sid | upper }}/HDB{{ db_instance_number }}/exe
        SAPSYSTEMNAME:                 "{{ db_sid | upper }}"


    - name:                            "4.0.1.6 Hana System Replication - Debug replication"
      ansible.builtin.debug:
        msg:                           "System replication status {{ systemReplicationStatus }}"
