---

- name:                                "4.1.3 Oracle Data Guard - Preparation - Set DB Path "
  ansible.builtin.set_fact:
    db_path:                           "{% if node_tier == 'oracle-asm' %}GRID{% else %}{{ db_sid | upper }}{% endif %}"

- name:                                "4.1.3 Oracle Data Guard - Check ASM status"
  become_user:                         "{{ grid_user_name }}"
  when:                                node_tier == "oracle-asm"
  become:                              true
  ansible.builtin.shell: |
                                       sqlplus -S / as sysasm <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF
                                       SELECT name || ':' || state FROM v\$asm_diskgroup;
                                       EXIT;
                                       EOF

  register:                            asm_status
  environment:                         "{{ grid_env }}"
  changed_when:                        false
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"

- name:                                "4.1.3 Oracle Data Guard - Show ASM mounted disk groups"
  ansible.builtin.debug:
    msg:                               "ASM Disk group Status: {{ asm_status.stdout }}"
  when:
    - node_tier == "oracle-asm"
    - asm_status is defined

- name:                                "4.1.3 Oracle Data Guard - Setup Primary - Validate ASM mounted disk groups"
  ansible.builtin.assert:
    that:                              "'MOUNTED' in asm_status.stdout"
    fail_msg:                          "ASM disk groups not mounted"
  when:
    - node_tier == "oracle-asm"
    - asm_status is defined

- name:                                "4.1.3 Oracle Data Guard - Verify Status on Primary"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       sqlplus -S / as sysdba <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF HEADING OFF;
                                       SELECT database_role || ':' || open_mode FROM v\$database;
                                       EXIT;
                                       EOF

  register:                            dg_status
  changed_when:                        false
  failed_when:                         false
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
  environment:                         "{{ oracle_env }}"

- name:                                "4.1.3 Oracle Data Guard - Set status on Primary"
  ansible.builtin.set_fact:
    primary_open:                      "{{ (dg_status.stdout is search('PRIMARY:READ WRITE')) | bool }}"
    primary_mounted:                   "{{ (dg_status.stdout is search('PRIMARY:MOUNTED')) | bool }}"
    needs_mounting:                    "{{ (dg_status.stdout is search('ORA-01507')) | bool }}"
    primary_exclusive:                 "{{ (dg_status.stdout is search('ORA-01102')) | bool }}"

- name:                                "4.1.3 Oracle Data Guard - Show status on Primary"
  ansible.builtin.debug:
    msg:
      - "Database instance:               {{ ansible_hostname }}"
      - "Primary mounted status:          {{ primary_mounted or primary_open }}"
      - "Primary open status:             {{ primary_open }}"
      - "Primary instance needs mounting: {{ needs_mounting }}"
      - "Primary instance open_mode:      {{ dg_status.stdout }}"

- name:                                "4.1.3 Oracle Data Guard - Restart Primary instance"
  when:
    - needs_mounting or primary_exclusive
  block:
    - name:                            "4.1.3 Oracle Data Guard: - Restart Primary instance"
      ansible.builtin.include_tasks:   "00-restart-instance.yaml"
      vars:
        current_sid:                   "{{ db_sid | upper }}"
        use_pfile_on_startup:          false

- name:                                "4.1.3 Oracle Data Guard - Mount Primary instance"
  when:
    - not primary_mounted
    - not primary_open
    - needs_mounting
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       sqlplus -S / as sysdba <<EOF
                                       WHENEVER SQLERROR EXIT SQL.SQLCODE
                                       ALTER DATABASE MOUNT;
                                       ALTER DATABASE OPEN;
                                       EXIT;
                                       EOF

  register:                            db_mounted
  changed_when:                        false
  failed_when:                         false
  environment:                         "{{ oracle_env }}"
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"

- name:                                "4.1.3 Oracle Data Guard - Verify Status on Primary"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       sqlplus -S / as sysdba <<EOF
                                       SET PAGESIZE 0 FEEDBACK OFF HEADING OFF;
                                       SELECT database_role || ':' || open_mode FROM v\$database;
                                       EXIT;
                                       EOF

  register:                            dg_status
  changed_when:                        false
  failed_when:                         false
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"
  environment:                         "{{ oracle_env }}"

- name:                                "4.1.3 Oracle Data Guard - Set status on Primary"
  ansible.builtin.set_fact:
    primary_open:                      "{{ (dg_status.stdout is search('PRIMARY:READ WRITE')) | bool }}"
    primary_mounted:                   "{{ (dg_status.stdout is search('PRIMARY:MOUNTED')) | bool }}"
    needs_mounting:                    "{{ (dg_status.stdout is search('ORA-01507')) | bool }}"

- name:                                "4.1.3 Oracle Data Guard - Show status on Primary"
  ansible.builtin.debug:
    msg:
     - "Primary mounted status:       {{ primary_mounted or primary_open }}"
     - "Primary open status:          {{ primary_open }}"
     - "Primary instance open_mode:   {{ dg_status.stdout }}"

- name:                                "4.1.3 Oracle Data Guard - Open Primary"
  when:
    - not primary_open
    - primary_mounted
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       sqlplus -S / as sysdba <<EOF
                                       WHENEVER SQLERROR EXIT SQL.SQLCODE
                                       ALTER DATABASE OPEN;
                                       EXIT;
                                       EOF

  register:                            db_opened
  changed_when:                        false
  failed_when:                         false
  environment:                         "{{ oracle_env }}"
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"

- name:                                "4.1.3 Oracle Data Guard - Verify Data Guard configuration on Primary"
  become_user:                         "{{ oracle_user_name }}"
  become:                              true
  ansible.builtin.shell: |
                                       sqlplus -S / as sysdba <<EOF
                                       WHENEVER SQLERROR EXIT SQL.SQLCODE
                                       SET PAGESIZE 0 FEEDBACK OFF HEADING OFF;
                                       SELECT database_role || ':' || open_mode FROM v\$database;
                                       EXIT;
                                       EOF

  register:                            dg_status
  changed_when:                        false
  failed_when:                         false
  environment:                         "{{ oracle_env }}"
  args:
    chdir:                             "/etc/sap_deployment_automation/dataguard_scripts/"

- name:                                "4.1.3 Oracle Data Guard - Get status from Primary"
  ansible.builtin.set_fact:
    primary_open:                      "{{ (dg_status.stdout is search('PRIMARY:READ WRITE')) | bool }}"
    primary_mounted:                   "{{ (dg_status.stdout is search('PRIMARY:MOUNTED')) | bool }}"
    needs_mounting:                    "{{ (dg_status.stdout is search('ORA-01507')) | bool }}"

- name:                                "4.1.3 Oracle Data Guard - Show status on Primary"
  ansible.builtin.debug:
    msg:
      - "Database instance:            {{ ansible_hostname }}"
      - "Primary mounted status:       {{ primary_mounted or primary_open }}"
      - "Primary open status:          {{ primary_open }}"
      - "Primary instance open_mode:   {{ dg_status.stdout }}"
