# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                          AZ CLI Identity Details                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
# TODO: switch over to azure.azcollection.azure_rm_account_info:
# - name:                                 "SCR Keys: ({{ function | upper }}) Get Subscription and Identity details"
#   delegate_to:                          localhost
#   azure.azcollection.azure_rm_account_info:
#     # auth_source:                      msi
#     # client_id:                        "{{ msi_client_id | default(omit) }}"
#   register:                             _results
#   run_once:                             true

- name:                                 "SCR Keys: ({{ function | upper }}) Get Subscription and Identity details (controller only)"
  delegate_to:                          localhost
  ansible.builtin.command: >-
    az account show
  register:                             _results
  run_once:                             true
  tags:
    - silent_v1



- name:                                 "SCR Keys: ({{ function | upper }}) Show Subscription and Identity details (controller only)"
  delegate_to:                          localhost
  ansible.builtin.debug:
    msg: |
                                        On Behalf of:                     {{ inventory_hostname }}
                                        Subscription:                     {{ (_results.stdout | from_json).id }}
                                        Identity:                         {{ (_results.stdout | from_json).user.assignedIdentityInfo }}

                                        Calling Parameters
                                        -------------------------------------------------
                                        function:                         {{ function                     | default('-') }}
                                        granularity:                      {{ granularity                  | default('-') }}
                                        prefix:                           {{ prefix                       | default('-') }}
                                        kv_name:                          {{ kv_name                      | default('-') }}
                                        inventory_hostname:               {{ inventory_hostname           | default('-') }}

                                        Host Facts
                                        -------------------------------------------------
                                        ansible_user:                     {{ ansible_user                 | default('-') }}
                                        ansible_ssh_private_key_file:     {{ ansible_ssh_private_key_file | default('-') }}
                                        ansible_ssh_common_args:          {{ ansible_ssh_common_args      | default('-') }}
                                        _scr_username_{{ granularity }}:         {{ lookup('vars', '_scr_username_' + granularity) }}
                                        _scr_sshkey_{{ granularity }}:           {{ lookup('vars', '_scr_sshkey_'   + granularity) }}
    verbosity: 1


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       SSH Credentials - Username                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                 "SCR Keys: ({{ function | upper }}) Fetch SSH Username from Key Vault (controller only)"
  delegate_to:                          localhost
  no_log:                               true
  block:
    - name:                             "SCR Keys: ({{ function | upper }}) Fetch SSH Username from Key Vault (controller only)"
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri:                      "https://{{ kv_name | lower }}.vault.azure.net/"
        name:                           "{{ lookup('vars', '_scr_username_' + granularity) }}"
        auth_source:                    msi
        client_id:                      "{{ msi_client_id | default(omit) }}"
      register:                         _results
      retries:                          5
      delay:                            1
      tags:
        - silent_v2

    - name:                             "SCR Keys: ({{ function | upper }}) Set per-host Username for SSH (controller only)"
      ansible.builtin.set_fact:
        ansible_user:                   "{{ _results.secrets[0].secret | default('UNSUPPORTED GRANULARITY') }}"
      tags:
        - silent_v2


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                        SSH Credentials - Private Key                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                     "SCR Keys: ({{ function | upper }}) Fetch SSH private key from Key Vault (controller only)"
  delegate_to:                              localhost
  no_log:                                   true
  block:
    - name:                                 "SCR Keys: ({{ function | upper }}) Fetch SSH private key from Key Vault (controller only)"
      azure.azcollection.azure_rm_keyvaultsecret_info:
        vault_uri:                          "https://{{ kv_name | lower }}.vault.azure.net/"
        name:                               "{{ lookup('vars', '_scr_sshkey_'   + granularity) }}"
        auth_source:                        msi
        client_id:                          "{{ msi_client_id | default(omit) }}"
      register:                             _results
      retries:                              5
      delay:                                1
      tags:
        - silent_v2

    - name:                                 "SCR Keys: ({{ function | upper }}) Store keys when defined (controller only)"
      block:

        - name:                             "SCR Keys: ({{ function | upper }}) Put private key into a temp file on controller (0600) (controller only)"
          ansible.builtin.copy:
            content:                        "{{ _results.secrets[0].secret }}"
            dest:                           "/tmp/ansible_kv_key_{{ inventory_hostname }}"
            mode:                           "0600"
          tags:
            - silent_v2

        - name:                             "SCR Keys: ({{ function | upper }}) Set per-host Private Key file path for SSH (controller only)"
          ansible.builtin.set_fact:
            ansible_ssh_private_key_file:   "/tmp/ansible_kv_key_{{ inventory_hostname }}"
          tags:
            - silent_v2

      when:                                 _results.secrets[0].secret is defined

    - name:                                 "SCR Keys: ({{ function | upper }}) Key Undefined (controller only)"
      ansible.builtin.set_fact:
        ansible_ssh_private_key_file:       "UNSUPPORTED GRANULARITY"
      when:                                 _results.secrets[0].secret is undefined


# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                           SSH Credentials - Recap                          |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
- name:                                 "SCR Keys: ({{ function | upper }}) Recap - Show Facts (controller only)"
  delegate_to:                          localhost
  ansible.builtin.debug:
    msg: |-
                                        Recap of Facts {{ ' ' * 22 }} Value
                                        {{ '-' * 29 }}{{ ' ' * 9 }}{{ '-' * 33 }}
                                        ansible_user:                         {{ ansible_user                 | default('-') }}
                                        ansible_ssh_private_key_file:         {{ ansible_ssh_private_key_file | default('-') }}
                                        ansible_ssh_common_args:              {{ ansible_ssh_common_args      | default('-') }}
    verbosity:                          0

...
