# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*---------------------------------------------------------------------------8
# |                                                                            |
# |          Role variables for the SAP Automation QA setup role               |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

sap_automation_qa_repository_url:      "https://github.com/{{ sap_automation_qa_fork }}/sap-automation-qa.git"
sap_automation_qa_source_directory:    "{{ sap_automation_qa_directory }}/src"

sap_automation_qa_collections_path:    "{{ sap_automation_qa_directory }}/.ansible/collections"
sap_automation_qa_collection_requirements: "{{ sap_automation_qa_directory }}/collections/requirements.yml"

sap_automation_qa_requirements:        "{{ sap_automation_qa_directory }}/requirements.txt"
sap_automation_qa_virtualenv:          "{{ sap_automation_qa_directory }}/.venv"

sap_automation_qa_input_api:           "{{ sap_automation_qa_source_directory }}/vars/input-api.yaml"
sap_automation_qa_filter_script:       "{{ sap_automation_qa_source_directory }}/module_utils/filter_tests.py"

sap_automation_qa_workspace_directory: "{{ sap_automation_qa_system_directory | default('', true) | ternary(sap_automation_qa_system_directory, _workspace_directory) }}"

sap_automation_qa_artifacts_directory: "{{ sap_automation_qa_workspace_directory }}/artifacts"
sap_automation_qa_selection_file:      "{{ sap_automation_qa_artifacts_directory }}/qa_test_selection.json"
sap_automation_qa_results_directory:   "{{ sap_automation_qa_workspace_directory }}/quality_assurance"
sap_automation_qa_logs_directory:      "{{ sap_automation_qa_workspace_directory }}/logs"
