---
name: trivy

on:
  pull_request:
    types: [ 'opened', 'reopened', 'synchronize' ]
  merge_group:
  workflow_dispatch:


permissions: {}

jobs:
  build:
    name: 'trivy scan'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Run Trivy vulnerability scanner (file system)
      uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297 # 0.34.2
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        scan-ref: .
        format: 'sarif'
        scanners: 'vuln,secret,config'
        output: report-fs.sarif

    - name: Upload Trivy report (fs) GitHub Security
      uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
      with:
        sarif_file: report-fs.sarif
        category: 'fs'
