# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# Inputs:
#    current_bom_name              - Name of BoM (ex: S41909SPS03_v0001ms)
#
#
# Outputs:
#   bom                   - object
#

---
# -------------------------------------+---------------------------------------8
#
# Description:  Check if BoM is Microsoft supplied and register BoM as an object.
#               If not, download from storage account location.
#

# -------------------------------------+---------------------------------------8
# Step: 01
# Description:  Create download directory structure
#
- name:                                 "3.3.1 BoM Processing - Create BoM download directories"
  ansible.builtin.file:
    path:                               "{{ item }}"
    state:                              directory
    mode:                               0755
    owner:                              "{{ orchestration_ansible_user if bom_processing_become else omit }}"
  delegate_to:                          localhost
  become:                               "{{ bom_processing_become }}"
  become_user:                          root
  loop:
    - "{{ download_directory }}"
    - "{{ download_directory }}/tmp"
    - "{{ download_directory }}/bom"
    - "{{ download_directory }}/files"
# Step: 01 - END
# -------------------------------------+---------------------------------------8


# -------------------------------------+---------------------------------------8
# Step: 02
# Description:  Set Python version
#
# Step: 02 - END
# -------------------------------------+---------------------------------------8

- name:                                "3.3.1 BoM Processing - Set the new name"
  ansible.builtin.set_fact:
    this_bom_name:                      "{{ current_bom_name | default(bom_base_name + bom_suffix) }}"

- name:                                "3.3.1 BoM Processing - Show the new name"
  ansible.builtin.debug:
    msg:
      - "BoM Name:   {{ this_bom_name }}"

- name:                                "3.3.1 BoM Processing - Reset the variables"
  ansible.builtin.set_fact:
    bom_file:                      ""
    from_storage_account:          false
    bom_found:                     false
    bom_path:                      ""

# -------------------------------------+---------------------------------------8
# Step: 03
# Description:  Check Storage Account for BoM when SA is enabled
#
- name:                                 "3.3.1 BoM Processing - Check Storage Account for BoM block"
  when:
    - sa_enabled | default(true)                                                 # when true; if not defined, then value is false
    # - sa_enabled is defined
    # - sa_enabled

    # - sa_enabled is not defined or sa_enabled | bool
  block:

# -------------------------------------+---------------------------------------8
# Step: 03-01
# Description:
#
    - name:                             "3.3.1 BoM Processing - Download {{ this_bom_name }} from the storage account"
      ansible.builtin.get_url:
        url:                            "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ this_bom_name }}/{{ this_bom_name }}.yaml\
                                        {% if sapbits_sas_token is defined %}?{{ sapbits_sas_token }}{% endif %}"
        dest:                           "{{ download_directory }}/bom/{{ this_bom_name }}.yaml"
        mode:                           0644
        validate_certs:                 false
      delegate_to:                      localhost
      become:                           "{{ bom_processing_become }}"
      ignore_errors:                    true
      register:                         result
# Step: 03-01 - END
# -------------------------------------+---------------------------------------8


# -------------------------------------+---------------------------------------8
# Step: 03-03
# Description:
#
    - name:                             "3.3.1 BoM Processing - Show BoM download status"
      ansible.builtin.debug:
        msg:
          - "URL:    {{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ this_bom_name }}/{{ this_bom_name }}.yaml{% if sapbits_sas_token is defined %}?{{ sapbits_sas_token }}{% endif %}"
          - "Result: {{ result }}"
        verbosity:                      2
# Step: 03-03 - END
# -------------------------------------+---------------------------------------8

# Step: 03 - END
# -------------------------------------+---------------------------------------8


# -------------------------------------+---------------------------------------8
# Step: 04
# Description:  Register BoM if found in Storage Account
#
- name:                                "3.3.1 BoM Processing - Retrieve BoM ({{  this_bom_name }}) from Storage Account"
  when:
    - result is succeeded or result is skipped
    - sa_enabled | default(false)
  block:

    # -------------------------------------+---------------------------------------8
    # Step: 04-01
    # Description:
    #
    - name:                            "{{ task_prefix }} Register downloaded BoM ({{  this_bom_name }})"
      ansible.builtin.include_vars:
        file:                          "{{ download_directory }}/bom/{{ this_bom_name }}.yaml"
        name:                          bom_temp
    # Step: 04-01 - END
    # -------------------------------------+---------------------------------------8

    # -------------------------------------+---------------------------------------8
    # Step: 04-02
    # Description:
    #
    - name:                             "{{ task_prefix }} Register downloaded BoM ({{  this_bom_name }})s file name"
      ansible.builtin.set_fact:
        bom_file:                      "{{ download_directory }}/bom/{{ this_bom_name }}.yaml"
        aggregated_bom_directories:    "{{ aggregated_bom_directories | default([]) + [{'path': path, 'location': 'sa'}] }}"
        from_storage_account:          true
        bom_found:                     true
        bom_path:                      "{{ download_directory }}/bom/{{ this_bom_name }}.yaml"
        local_media_list:              "{{ bom_temp.materials.media | flatten(levels=1) }}"

      vars:
        path:                          "{{ sapbits_location_base_path }}/{{ sapbits_bom_files }}/boms/{{ this_bom_name }}"
    # Step: 04-02 - END
    # -------------------------------------+---------------------------------------8

    # Step: 04 - END
    # -------------------------------------+---------------------------------------8


# -------------------------------------+---------------------------------------8
# Step: 05
# Description:  Check for MS provided BoM if not in SA
#
- name:                                "{{ task_prefix }} Check for Microsoft Supplied BoM ({{  this_bom_name }})"
  when:
    - result is failed or always_upload_jinja_templates or (sa_enabled is defined and not sa_enabled)
    - not (from_storage_account | default(false))
  # when:                                 result is failed or always_upload_jinja_templates or sa_enabled is not defined or not sa_enabled
  block:

    # -------------------------------------+---------------------------------------8
    # Step: 05-01
    # Description:
    #
    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BoM ({{  this_bom_name }}) in {{ BOM_directory }}/SAP"
      ansible.builtin.stat:
        path:                          "{{ BOM_directory }}/SAP/{{  this_bom_name }}/{{ this_bom_name }}.yaml"
      register:                        microsoft_supplied_bom
      delegate_to:                     localhost
      become:                          "{{ bom_processing_become }}"
      failed_when:                     false

    - name:                            "{{ task_prefix }} Show Microsoft Supplied BoM ({{ this_bom_name }}) result"
      ansible.builtin.debug:
        msg: |-
                                       BoM PATH:   {{ BOM_directory }}/SAP/{{  this_bom_name }}/{{ this_bom_name }}.yaml
                                       BoM Exists: {{ microsoft_supplied_bom.stat.exists }}
        verbosity:                     0

    - name:                            "{{ task_prefix }} Microsoft Supplied BoM ({{ this_bom_name }}) result"
      ansible.builtin.set_fact:
        bom_found:                     "{{ microsoft_supplied_bom.stat.exists | default(false) }}"
        bom_path:                      "{{ microsoft_supplied_bom.stat.path | default('') }}"

    # Step: 05-01 - END
    # -------------------------------------+---------------------------------------8

    # -------------------------------------+---------------------------------------8
    # Step: 05-02
    # Description:
    #
    # Step: 05-02 - END
    # -------------------------------------+---------------------------------------8
    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BoM ({{  this_bom_name }}) in {{ BOM_directory }}/BoM"
      when:                            not bom_found
      block:
        - name:                        "{{ task_prefix }} Check for Microsoft Supplied BoM ({{  this_bom_name }}) in {{ BOM_directory }}/BoM"
          ansible.builtin.stat:
            path:                      "{{ BOM_directory }}/BOM/{{  this_bom_name }}/{{  this_bom_name }}.yaml"
          register:                    microsoft_supplied_bom
          delegate_to:                 localhost
          become:                      "{{ bom_processing_become }}"
          failed_when:                 false

        - name:                        "{{ task_prefix }} Show Microsoft Supplied BoM ({{ this_bom_name }}) result"
          ansible.builtin.debug:
            msg: |-
                                      BoM PATH:   {{ BOM_directory }}/BOM/{{  this_bom_name }}/{{ this_bom_name }}.yaml
                                      BoM Exists: {{ microsoft_supplied_bom.stat.exists | default(false) }}

        - name:                            "{{ task_prefix }} Microsoft Supplied BoM ({{ this_bom_name }}) result"
          ansible.builtin.set_fact:
            bom_found:                     "{{ microsoft_supplied_bom.stat.exists | default(false) }}"
            bom_path:                      "{{ microsoft_supplied_bom.stat.path | default('Not Found') }}"


    # -------------------------------------+---------------------------------------8
    # Step: 05-03
    # Description:
    #
    - name:                            "{{ task_prefix }} Register Microsoft Supplied BoM {{  this_bom_name }}"
      when:                            bom_found
      ansible.builtin.include_vars:
        file:                          "{{ bom_path }}"
        name:                          bom_temp


    # Step: 05-03 - END
    # -------------------------------------+---------------------------------------8

    # -------------------------------------+---------------------------------------8
    # Step: 05-04
    # Description:
    #
    - name:                            "{{ task_prefix }} Register Microsoft Supplied BoM ({{  this_bom_name }}) facts"
      when:                            bom_found
      ansible.builtin.set_fact:
        bom:                           "{{ bom_temp }}"
        bom_file:                      "{{ bom_path }}"
        aggregated_bom_directories:    "{{ aggregated_bom_directories | default([]) + [{'path': path, 'location': 'local'}] }}"
      vars:
        path:                          "{{ bom_path | dirname }}"

    - name:                            "{{ task_prefix }} Append the file list"
      ansible.builtin.set_fact:
        local_media_list:              "{{ bom_temp.materials.media | flatten(levels=1) }}"
      when:
        - bom_temp is defined
        - bom_temp.materials is defined
        - bom_temp.materials.media is defined

    # Step: 05-04 - END
    # -------------------------------------+---------------------------------------8

    # -------------------------------------+---------------------------------------8
    # Step: 05-05
    # Description:
    #
    - name:                            "{{ task_prefix }} Check for Microsoft Supplied BoM ({{  this_bom_name }}) in archives"
      when:                            not bom_found
      block:

      # -------------------------------------+---------------------------------------8
      # Step: 05-05-01
      # Description:
      #
        - name:                         "{{ task_prefix }} Check for Microsoft Supplied BoM ({{  this_bom_name }}) in archives"
          ansible.builtin.stat:
            path:                       "{{ BOM_directory }}/archives/{{  this_bom_name }}/{{  this_bom_name }}.yaml"
          register:                     microsoft_supplied_bom_archive
          delegate_to:                  localhost
          become:                       "{{ bom_processing_become }}"
          failed_when:                  false
      # Step: 05-05-01 - END
      # -------------------------------------+---------------------------------------8

      # -------------------------------------+---------------------------------------8
      # Step: 05-05-02
      # Description:
      #
        - name:                         "{{ task_prefix }} Register Microsoft Supplied BoM {{  this_bom_name }} from archives"
          ansible.builtin.include_vars:
            file:                       "{{ microsoft_supplied_bom_archive.stat.path }}"
            name:                       bom_temp
          when:                         microsoft_supplied_bom_archive.stat.exists
          # Step: 05-05-02 - END
          # -------------------------------------+---------------------------------------8

          # -------------------------------------+---------------------------------------8
          # Step: 05-05-03
          # Description:
          #
        - name:                         "{{ task_prefix }} Register Microsoft Supplied BoM ({{  this_bom_name }}) facts"
          when:                         microsoft_supplied_bom_archive.stat.exists
          ansible.builtin.set_fact:
            bom:                        "{{ bom_temp }}"
            bom_file:                   "{{ microsoft_supplied_bom_archive.stat.path }}"
            aggregated_bom_directories: "{{ aggregated_bom_directories | default([]) + [{'path': path, 'location': 'local'}] }}"
          vars:
            path:                       "{{ microsoft_supplied_bom_archive.stat.path | dirname }}"

        - name:                        "{{ task_prefix }} Append the file list"
          ansible.builtin.set_fact:
            local_media_list:          "{{ bom_temp.materials.media | flatten(levels=1) }}"
          when:
            - bom_temp is defined
            - bom_temp.materials is defined
            - bom_temp.materials.media is defined

          # Step: 05-05-03 - END
          # -------------------------------------+---------------------------------------8

# -------------------------------------+---------------------------------------8
# Step: 06
# Description:  Validate that BoM was found
#

- name:                                "{{ task_prefix }} Validate that a BoM object is created"
  when:                                bom_temp is not defined
  ansible.builtin.fail:
    msg:                               "Unable to find the Bill of materials file for {{  this_bom_name }}."

- name:                                "{{ task_prefix }} Show BoM object"
  when:
    - operation | default('Download') == "SoftwareAcquisition"
    - bom_temp is defined
  ansible.builtin.debug:
    msg:
      - "BoM: {{ bom_temp }}"
      - "Media: {{ local_media_list }}"
      - "Patch information: {{ patch_information | default('No patch information') }}"
    verbosity:                          2

- name:                                "{{ task_prefix }} Set BoM object"
  when:
    - bom_temp is defined
  ansible.builtin.set_fact:
    bom:                               "{{ bom_temp }}"

# Step: 06 - END
# -------------------------------------+---------------------------------------8


# -------------------------------------+---------------------------------------8
# Step: 07
# Description:  Show BoM detail
#
- name:                                 "{{ task_prefix }} Show BoM details"
  ansible.builtin.debug:
    msg:
      - "BoM name:        {{ bom_temp.name }}"
      - "BoM target:      {{ bom_temp.target }}"
      - "BoM version:     {{ bom_temp.version }}"
      - "BoM DB platform: {% if bom_temp.platform is defined %}{{ bom_temp.platform }}{% else %}Not defined{% endif %}"
      - "Instance type:   {% if bom_temp.InstanceType is defined %}{{ bom_temp.InstanceType }}{% else %}Not defined{% endif %}"
  when:
    - operation | default('Download') == "SoftwareAcquisition"
    - bom_temp is defined
    - bom_temp.name is not search('SWPM')
    - bom_temp.name is not search('SUM')
# Step: 07 - END
# -------------------------------------+---------------------------------------8


# -------------------------------------+---------------------------------------8
# Step: 08
# Description:  Validate that BoM was found
#
# ToDo Add this back later, Kimmo Jan 25
# - name:                                 "{{ task_prefix }} Ensure that a BoM platform is defined"
#   ansible.builtin.assert:
#     that:
#       - bom.platform is defined                                                 # Has the variable been defined
#       - bom.platform | upper == platform | upper
#     fail_msg:                           "The BoM {{  current_bom_name }} is not for platform {{ platform }}"
#   when:
#     - platform is defined
#     - platform | length > 2
# Step: 08 - END
# -------------------------------------+---------------------------------------8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
